"""
AutoForensic AI — AI-Generated Image & Inpainting Detector
=============================================================
Security Layer 5: Detects AI-generated or AI-inpainted vehicle damage
images by analyzing sensor noise residuals, frequency-domain artifacts,
and local patch-level inconsistencies that distinguish synthetic pixels
from physical camera sensor output.

Detection Techniques:
    1. Sensor Noise Residual Analysis (PRNU-inspired)
       Physical camera sensors produce consistent Poisson-Gaussian noise
       patterns (Photo-Response Non-Uniformity). AI diffusion models
       generate synthetic pixels lacking this physical sensor signature,
       producing characteristically different noise statistics.

    2. 2D-FFT Spectral Frequency Analysis
       Convolutional and diffusion upsamplers leave periodic checkerboard
       artifacts in the frequency domain. The 2D Fast Fourier Transform
       magnitude spectrum reveals unnatural radial frequency spikes and
       grid patterns not present in natural optical photographs.

    3. Local Patch Anomaly Scanner (Sliding Window)
       Divides the image into overlapping grid patches and compares each
       patch's noise variance, Laplacian sharpness energy, and frequency
       profile against its spatial neighbors. AI-inpainted regions exhibit
       dramatic local discontinuities (e.g., 3x+ noise disparity vs.
       adjacent panels on the same car body surface).

References:
    - Fridrich, J. & Kodovsky, J. (2012). "Rich Models for Steganalysis
      of Digital Images" IEEE TIFS.
    - Marra, F. et al. (2019). "Do GANs Leave Artificial Fingerprints?"
      IEEE MIPR.
    - Frank, J. et al. (2020). "Leveraging Frequency Analysis for Deep
      Fake Image Recognition" ICML.
    - Corvi, R. et al. (2023). "On The Detection of Synthetic Images
      Generated by Diffusion Models" ICASSP.
"""

import io
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import cv2
import numpy as np

logger = logging.getLogger("autoforensic.forensics.ai_detector")


# ══════════════════════════════════════════════════════════════
# RESULT DATACLASS
# ══════════════════════════════════════════════════════════════

class AIDetectionResult:
    """Structured result from AI-generated image detection analysis."""

    def __init__(
        self,
        is_ai_suspected: bool,
        noise_score: float,
        spectral_score: float,
        patch_score: float,
        overall_ai_score: float,
        noise_metrics: dict,
        spectral_metrics: dict,
        patch_metrics: dict,
        risk_flags: Optional[list] = None,
        authenticity_score: float = 100.0,
        heatmap: Optional[np.ndarray] = None,
        heatmap_path: Optional[str] = None,
    ):
        self.is_ai_suspected = is_ai_suspected
        self.noise_score = noise_score          # 0-100, lower = more AI-like
        self.spectral_score = spectral_score    # 0-100, lower = more AI-like
        self.patch_score = patch_score          # 0-100, lower = more AI-like
        self.overall_ai_score = overall_ai_score
        self.noise_metrics = noise_metrics
        self.spectral_metrics = spectral_metrics
        self.patch_metrics = patch_metrics
        self.risk_flags = risk_flags or []
        self.authenticity_score = authenticity_score
        self.heatmap = heatmap
        self.heatmap_path = heatmap_path

    def save_heatmap(self, output_path: Union[str, Path]) -> Optional[str]:
        """Save the AI inpainting anomaly heatmap overlay to disk."""
        if self.heatmap is None:
            return None
        try:
            out_p = Path(output_path)
            out_p.parent.mkdir(parents=True, exist_ok=True)
            cv2.imwrite(str(out_p), self.heatmap)
            self.heatmap_path = str(out_p)
            return str(out_p)
        except Exception as e:
            logger.error("Failed to save AI inpainting heatmap: %s", e)
            return None

    def to_dict(self) -> dict:
        d = {
            "is_ai_suspected": self.is_ai_suspected,
            "noise_score": round(self.noise_score, 2),
            "spectral_score": round(self.spectral_score, 2),
            "patch_score": round(self.patch_score, 2),
            "overall_ai_score": round(self.overall_ai_score, 2),
            "noise_metrics": {
                k: round(v, 4) if isinstance(v, float) else v
                for k, v in self.noise_metrics.items()
            },
            "spectral_metrics": {
                k: round(v, 4) if isinstance(v, float) else v
                for k, v in self.spectral_metrics.items()
            },
            "patch_metrics": {
                k: round(v, 4) if isinstance(v, float) else v
                for k, v in self.patch_metrics.items()
            },
            "risk_flags": self.risk_flags,
            "authenticity_score": round(self.authenticity_score, 2),
        }
        if self.heatmap_path:
            d["heatmap_path"] = self.heatmap_path
        return d

    def __repr__(self) -> str:
        status = "AI_SUSPECTED" if self.is_ai_suspected else "NATURAL"
        return (
            f"AIDetectionResult({status}, "
            f"noise={self.noise_score:.1f}, "
            f"spectral={self.spectral_score:.1f}, "
            f"patch={self.patch_score:.1f}, "
            f"ai_score={self.overall_ai_score:.1f}%, "
            f"auth_score={self.authenticity_score:.1f}%)"
        )


# ══════════════════════════════════════════════════════════════
# AI DETECTION ENGINE
# ══════════════════════════════════════════════════════════════

class AIDetector:
    """
    Detects AI-generated or AI-inpainted regions in vehicle damage photos.

    Combines three complementary forensic techniques:
    1. Sensor Noise Residual: Extracts high-pass noise and measures
       consistency with physical camera PRNU patterns.
    2. 2D-FFT Spectral Analysis: Detects periodic upsampling artifacts
       characteristic of GAN/diffusion model outputs.
    3. Local Patch Scanner: Identifies localized regions where noise
       statistics abruptly diverge from surrounding areas.

    Usage:
        >>> detector = AIDetector()
        >>> result = detector.analyze("path/to/car_damage.jpg")
        >>> print(result.is_ai_suspected)
        True
        >>> print(result.overall_ai_score)
        38.5
    """

    def __init__(
        self,
        patch_size: int = 32,
        patch_stride: int = 16,
        patch_sizes: Tuple[int, ...] = (32, 64),
        noise_disparity_threshold: float = 3.0,
        spectral_spike_threshold: float = 2.5,
        min_suspicious_patches_ratio: float = 0.03,
    ):
        """
        Args:
            patch_size: Primary sliding window patch size (pixels).
            patch_stride: Step between adjacent patches (pixels).
            patch_sizes: Multi-scale patch sizes for scanning (pixels).
            noise_disparity_threshold: Factor by which a patch's noise
                or sharpness must exceed neighbors to be flagged (default 2.5×).
            spectral_spike_threshold: Z-score threshold for frequency
                domain spike detection (default 2.5σ).
            min_suspicious_patches_ratio: Minimum fraction of suspicious
                patches to trigger AI detection flag (default 3%).
        """
        self.patch_size = patch_size
        self.patch_stride = patch_stride
        self.patch_sizes = patch_sizes
        self.noise_disparity_threshold = noise_disparity_threshold
        self.spectral_spike_threshold = spectral_spike_threshold
        self.min_suspicious_patches_ratio = min_suspicious_patches_ratio

    def analyze(self, image_input) -> AIDetectionResult:
        """
        Run the complete AI detection analysis on an image.

        Args:
            image_input: File path (str/Path), raw bytes, or numpy array (BGR).

        Returns:
            AIDetectionResult with detection metrics, scores, risk flags, and heatmap.
        """
        # Load image
        image = self._load_image(image_input)
        if image is None:
            return AIDetectionResult(
                is_ai_suspected=False,
                noise_score=50.0,
                spectral_score=50.0,
                patch_score=50.0,
                overall_ai_score=50.0,
                noise_metrics={"error": "Could not load image"},
                spectral_metrics={},
                patch_metrics={},
                risk_flags=["AI_DETECT_LOAD_FAILED: Could not load image"],
                authenticity_score=50.0,
            )

        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        risk_flags = []

        # ── Technique 1: Sensor Noise Residual Analysis ──
        noise_metrics, noise_score = self._analyze_noise_residual(gray)

        # ── Technique 2: 2D-FFT Spectral Frequency Analysis ──
        spectral_metrics, spectral_score = self._analyze_frequency_spectrum(gray)

        # ── Technique 3: Local Patch Anomaly Scanner ──
        patch_metrics, patch_score, heatmap = self._analyze_local_patches(gray, image)

        # ── Aggregate AI Detection Score ──
        # Weighted combination: noise (35%), spectral (30%), patch (35%)
        overall_ai_score = (
            noise_score * 0.35
            + spectral_score * 0.30
            + patch_score * 0.35
        )

        # ── Risk Flag Generation ──
        is_ai_suspected = False

        # 1. Noise residual anomaly flags
        kurt = noise_metrics.get("kurtosis", 0.0)
        if abs(kurt) > 18.0 and patch_score < 75.0:
            is_ai_suspected = True
            risk_flags.append(
                f"NOISE_ANOMALY: Sensor noise kurtosis ({kurt:.2f}) severely deviates from "
                f"physical camera sensor PRNU noise [-1.0, 3.0]. High probability of neural generation."
            )
        elif noise_score < 50.0:
            is_ai_suspected = True
            risk_flags.append(
                f"NOISE_ANOMALY: Sensor noise pattern inconsistent with natural camera output "
                f"(noise_score={noise_score:.1f}%, kurtosis={kurt:.2f})"
            )

        # 2. Spectral frequency anomaly flags
        # Corroborated with noise residual to avoid false positives on natural geometric textures
        max_z = spectral_metrics.get("max_z_score", 0.0)
        spikes = spectral_metrics.get("spike_count", 0)
        if (spikes >= 8 and max_z > 6.0 and noise_score < 60.0) or (spectral_score < 40.0 and noise_score < 60.0):
            is_ai_suspected = True
            risk_flags.append(
                f"SPECTRAL_ANOMALY: Frequency spectrum exhibits periodic grid spikes characteristic "
                f"of neural upsamplers/diffusion latents (spectral_score={spectral_score:.1f}%, "
                f"spikes={spikes}, max_z={max_z:.2f}σ)"
            )
        elif spectral_score < 50.0:
            risk_flags.append(
                f"SPECTRAL_ELEVATION: Frequency domain shows elevated high-frequency components "
                f"(spectral_score={spectral_score:.1f}%, spikes={spikes}, max_z={max_z:.2f}σ)"
            )

        # 3. Local patch anomaly flags
        max_disp = patch_metrics.get("max_noise_disparity", 1.0)
        susp_ratio = patch_metrics.get("suspicious_patch_ratio", 0.0)
        n_susp = patch_metrics.get("suspicious_patch_count", 0)
        n_total = patch_metrics.get("total_patches", 1)
        if (max_disp > 10.0 and susp_ratio > 0.02) or patch_score < 50.0:
            is_ai_suspected = True
            risk_flags.append(
                f"LOCAL_PATCH_ANOMALY: Multi-scale scan found {n_susp}/{n_total} suspicious patches "
                f"({susp_ratio * 100:.1f}%) with severe noise disparity (max {max_disp:.1f}×), "
                f"confirming localized AI inpainting / damage editing."
            )

        # 4. Overall score flag
        if overall_ai_score < 55.0:
            is_ai_suspected = True
            risk_flags.append(
                f"AI_GENERATION_CONFIRMED: Combined multi-technique analysis confirms synthetic AI "
                f"damage inpainting (overall AI score={overall_ai_score:.1f}%)."
            )

        # Authenticity score matches overall score
        authenticity_score = overall_ai_score

        return AIDetectionResult(
            is_ai_suspected=is_ai_suspected,
            noise_score=noise_score,
            spectral_score=spectral_score,
            patch_score=patch_score,
            overall_ai_score=overall_ai_score,
            noise_metrics=noise_metrics,
            spectral_metrics=spectral_metrics,
            patch_metrics=patch_metrics,
            risk_flags=risk_flags,
            authenticity_score=authenticity_score,
            heatmap=heatmap,
        )

    # ══════════════════════════════════════════════════════════════
    # TECHNIQUE 1: SENSOR NOISE RESIDUAL ANALYSIS
    # ══════════════════════════════════════════════════════════════

    def _analyze_noise_residual(self, gray: np.ndarray) -> Tuple[dict, float]:
        """
        Extract and analyze the high-pass sensor noise residual.

        Physical camera sensors produce noise with specific statistical
        properties (approximately Gaussian with characteristic kurtosis).
        AI-generated images have fundamentally different noise distributions
        because they synthesize pixels through neural network inference
        rather than photon counting.

        Method:
            R(x,y) = I(x,y) - MedianFilter(I(x,y), k=3)

        Metrics:
            - Noise variance: Spread of the residual distribution
            - Kurtosis: "Tailedness" — camera noise is near-Gaussian (k≈3),
              AI noise tends to be sharper/leptokurtic or flatter/platykurtic
            - Noise entropy: Information content of the residual pattern
        """
        # Extract noise residual via median filter subtraction
        median_filtered = cv2.medianBlur(gray, 3)
        residual = gray.astype(np.float64) - median_filtered.astype(np.float64)

        # Statistical metrics of the noise residual
        noise_mean = float(np.mean(np.abs(residual)))
        noise_var = float(np.var(residual))
        noise_std = float(np.std(residual))

        # Kurtosis (excess kurtosis: Gaussian = 0, camera noise ≈ 0-2)
        # Use an empirical camera sensor noise floor of 3.5 (8-bit quantization baseline)
        # in the denominator to prevent sample kurtosis from exploding on smooth/flat surfaces (e.g. white car paint)
        if noise_std > 1e-8:
            centered = residual - np.mean(residual)
            eff_std = max(noise_std, 3.5)
            kurtosis = float(
                np.mean(centered ** 4) / (eff_std ** 4) - 3.0
            )
        else:
            kurtosis = 0.0

        # Skewness (asymmetry measure)
        if noise_std > 1e-8:
            skewness = float(np.mean(centered ** 3) / (noise_std ** 3))
        else:
            skewness = 0.0

        # Noise entropy via histogram
        hist, _ = np.histogram(residual.flatten(), bins=256, range=(-128, 128))
        hist_norm = hist / (hist.sum() + 1e-10)
        entropy = float(-np.sum(hist_norm * np.log2(hist_norm + 1e-10)))

        # Laplacian variance (edge/texture energy — AI often over-smooths
        # or produces unnaturally sharp localized edges)
        laplacian = cv2.Laplacian(gray, cv2.CV_64F)
        laplacian_var = float(np.var(laplacian))

        # Noise-to-signal ratio in local blocks
        h, w = gray.shape
        block_size = 32
        local_noise_vars = []
        for y in range(0, h - block_size, block_size):
            for x in range(0, w - block_size, block_size):
                block = residual[y:y + block_size, x:x + block_size]
                local_noise_vars.append(float(np.var(block)))

        # Coefficient of variation of local noise (natural images have
        # consistent noise; AI images have patchy noise distributions)
        if local_noise_vars:
            local_var_mean = float(np.mean(local_noise_vars))
            local_var_std = float(np.std(local_noise_vars))
            noise_consistency = (
                local_var_std / (local_var_mean + 1e-8)
            )
        else:
            noise_consistency = 0.0
            local_var_mean = 0.0

        metrics = {
            "noise_mean": noise_mean,
            "noise_variance": noise_var,
            "noise_std": noise_std,
            "kurtosis": kurtosis,
            "skewness": skewness,
            "entropy": entropy,
            "laplacian_variance": laplacian_var,
            "noise_consistency_cv": noise_consistency,
            "local_variance_mean": local_var_mean,
        }

        # Scoring: map noise statistics to 0-100 authenticity score
        score = self._score_noise(metrics)

        return metrics, score

    def _score_noise(self, metrics: dict) -> float:
        """
        Score noise residual metrics (0-100, higher = more natural/authentic).

        Key indicators of AI generation:
        - Very high noise variance (AI diffusion models inject noise across flat panels)
        - Abnormal kurtosis (physical camera PRNU is near Gaussian, kurtosis in [-1, 6])
        - Very high noise consistency CV (patchy, inconsistent noise)
        """
        score = 100.0
        noise_var = metrics["noise_variance"]
        kurtosis = metrics["kurtosis"]
        entropy = metrics["entropy"]
        consistency_cv = metrics["noise_consistency_cv"]
        laplacian_var = metrics["laplacian_variance"]

        # 1. Penalize extremely high noise variance (AI diffusion models injecting artificial noise)
        if noise_var > 80.0:
            score -= 25.0
        elif noise_var > 50.0:
            score -= 10.0

        # 2. Penalize abnormal kurtosis
        abs_kurt = abs(kurtosis)
        if abs_kurt > 20.0:
            score -= 35.0
        elif abs_kurt > 14.0:
            score -= 20.0
        elif abs_kurt > 8.0:
            score -= 10.0

        # 3. Penalize high noise inconsistency (patchy AI artifacts)
        if consistency_cv > 2.8:
            score -= 20.0
        elif consistency_cv > 2.0:
            score -= 10.0
        elif consistency_cv > 1.5:
            score -= 5.0

        # 4. Only penalize if entropy is virtually zero (blank synthetic image)
        if entropy < 0.5:
            score -= 20.0

        # 5. Penalize extreme laplacian variance
        if laplacian_var > 4000.0:
            score -= 15.0

        return max(0.0, min(100.0, score))

    # ══════════════════════════════════════════════════════════════
    # TECHNIQUE 2: 2D-FFT SPECTRAL FREQUENCY ANALYSIS
    # ══════════════════════════════════════════════════════════════

    def _analyze_frequency_spectrum(self, gray: np.ndarray) -> Tuple[dict, float]:
        """
        Analyze the 2D FFT magnitude spectrum for AI generation artifacts.

        GAN and diffusion model outputs contain characteristic periodic
        patterns in the frequency domain:
        - Grid artifacts from transposed convolution (stride-based upsampling)
        - Radial frequency dropoffs that differ from natural lens+sensor PSF
        - Unusual mid-to-high frequency energy distribution

        Method:
            1. Compute 2D DFT and shift zero-frequency to center
            2. Extract magnitude spectrum (log scale)
            3. Compute radial power spectral density profile
            4. Detect abnormal spikes via z-score thresholding
            5. Compare radial decay slope to natural image statistics
        """
        h, w = gray.shape

        # Compute 2D DFT
        f_transform = np.fft.fft2(gray.astype(np.float64))
        f_shift = np.fft.fftshift(f_transform)
        magnitude = np.abs(f_shift)
        # Log magnitude for analysis (avoid log(0))
        log_magnitude = np.log1p(magnitude)

        # Center coordinates
        cy, cx = h // 2, w // 2
        max_radius = int(np.sqrt(cy ** 2 + cx ** 2))

        # Compute radial power spectral density (azimuthal average)
        Y, X = np.ogrid[:h, :w]
        radius_map = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2).astype(int)

        radial_psd = np.zeros(max_radius + 1)
        radial_counts = np.zeros(max_radius + 1)

        for r in range(max_radius + 1):
            mask = radius_map == r
            if np.any(mask):
                radial_psd[r] = float(np.mean(log_magnitude[mask]))
                radial_counts[r] = float(np.sum(mask))

        # Trim to valid range (radii with enough samples)
        valid_mask = radial_counts > 5
        valid_radii = np.where(valid_mask)[0]

        if len(valid_radii) < 10:
            return {
                "error": "Image too small for spectral analysis",
                "radial_psd_length": len(valid_radii),
            }, 75.0  # Neutral

        valid_psd = radial_psd[valid_mask]

        # ── Spike Detection ──
        # ── Spike Detection ──
        # Natural images have smooth radial PSD falloff.
        # AI artifacts create localized spikes above the smooth baseline.
        # Exclude low frequencies (radii < 15) where scene illumination and DC energy dominate
        valid_range = (valid_radii >= 15) & (valid_radii <= int(len(valid_psd) * 0.95))
        if np.sum(valid_range) > 10:
            eval_psd = valid_psd[valid_range]
            window = min(15, len(eval_psd) // 3)
            if window < 3:
                window = 3

            # Pad for convolution
            padded = np.pad(eval_psd, window // 2, mode="edge")
            baseline = np.convolve(padded, np.ones(window) / window, mode="valid")
            baseline = baseline[:len(eval_psd)]

            residual = eval_psd - baseline
            residual_std = float(np.std(residual))

            if residual_std > 1e-8:
                z_scores = residual / residual_std
            else:
                z_scores = np.zeros_like(residual)

            # Only count positive spikes above moving average baseline (AI upsampling artifacts)
            spike_count = int(np.sum(z_scores > self.spectral_spike_threshold))
            max_z = float(np.max(z_scores)) if len(z_scores) > 0 else 0.0
        else:
            residual_std = 0.0
            spike_count = 0
            max_z = 0.0

        # ── Spectral Decay Slope ──
        # Natural images: PSD ~ f^(-α) where α ∈ [1.5, 3.0]
        # AI images often have different slopes or plateau regions
        mid_start = len(valid_psd) // 4
        mid_end = 3 * len(valid_psd) // 4
        if mid_end > mid_start + 5:
            mid_range_psd = valid_psd[mid_start:mid_end]
            mid_range_radii = valid_radii[mid_start:mid_end]

            # Linear fit in log-log space for slope estimation
            log_radii = np.log(mid_range_radii.astype(float) + 1)
            if np.std(log_radii) > 1e-8:
                slope = float(np.polyfit(log_radii, mid_range_psd, 1)[0])
            else:
                slope = 0.0
        else:
            slope = 0.0

        # ── High-Frequency Energy Ratio ──
        # AI upsampling often has unusual high-frequency energy
        mid_freq = len(valid_psd) // 2
        if mid_freq > 0 and len(valid_psd) > mid_freq:
            low_energy = float(np.mean(valid_psd[:mid_freq]))
            high_energy = float(np.mean(valid_psd[mid_freq:]))
            hf_ratio = high_energy / (low_energy + 1e-8)
        else:
            hf_ratio = 0.0

        # ── Cross-shaped Artifact Detection ──
        # GAN artifacts often concentrate along horizontal/vertical axes
        center_h_strip = log_magnitude[cy - 2:cy + 3, :]
        center_v_strip = log_magnitude[:, cx - 2:cx + 3]
        cross_energy = float(np.mean(center_h_strip) + np.mean(center_v_strip))
        total_energy = float(np.mean(log_magnitude)) * 2
        cross_ratio = cross_energy / (total_energy + 1e-8)

        metrics = {
            "spike_count": spike_count,
            "spectral_slope": slope,
            "hf_energy_ratio": hf_ratio,
            "cross_artifact_ratio": cross_ratio,
            "max_z_score": max_z,
            "mean_residual_std": float(residual_std),
        }

        score = self._score_spectral(metrics)
        return metrics, score

    def _score_spectral(self, metrics: dict) -> float:
        """
        Score spectral metrics (0-100, higher = more natural/authentic).

        Key indicators of AI generation:
        - Many spectral spikes above baseline (periodic artifacts)
        - Abnormal spectral decay slope (not in natural range)
        - High cross-axis energy ratio (GAN grid artifacts)
        - Abnormal high-frequency energy ratio
        - High z-scores indicating periodic frequency spikes
        """
        score = 100.0
        spike_count = metrics.get("spike_count", 0)
        slope = metrics.get("spectral_slope", 0.0)
        hf_ratio = metrics.get("hf_energy_ratio", 0.0)
        cross_ratio = metrics.get("cross_artifact_ratio", 0.0)
        max_z = metrics.get("max_z_score", 0.0)

        # 1. Penalize many spectral spikes
        # For large images with 800+ radial frequency bins, normal fluctuations naturally yield 4-8 points > 2.5σ
        if spike_count > 15:
            score -= 25.0
        elif spike_count > 9:
            score -= 10.0
        elif spike_count > 4:
            score -= 5.0

        # 2. Penalize abnormal spectral slope
        #    Natural images: slope typically in [-3.0, -0.5]
        #    AI images: often flatter (slope > -0.3) or steeper (< -4.0)
        if slope > -0.3:
            score -= 15.0
        elif slope < -4.0:
            score -= 10.0

        # 3. Penalize very high cross-axis ratio (GAN grid artifacts)
        #    Natural images: ~1.0-1.3
        #    GAN images: >1.5
        if cross_ratio > 1.8:
            score -= 20.0
        elif cross_ratio > 1.4:
            score -= 10.0

        # 4. Penalize abnormal high-frequency energy
        #    Natural images have HF ratio typically 0.2-0.6
        #    AI upsampling creates abnormally high or low HF
        if hf_ratio > 0.85:
            score -= 15.0
        elif hf_ratio < 0.1:
            score -= 10.0

        # 5. Penalize extreme z-scores (strong periodic artifacts from transposed convolutions)
        if max_z > 8.0:
            score -= 20.0
        elif max_z > 6.0:
            score -= 10.0

        return max(0.0, min(100.0, score))

    # ══════════════════════════════════════════════════════════════
    # TECHNIQUE 3: LOCAL PATCH ANOMALY SCANNER (MULTI-SCALE)
    # ══════════════════════════════════════════════════════════════

    def _analyze_local_patches(
        self, gray: np.ndarray, orig_bgr: Optional[np.ndarray] = None
    ) -> Tuple[dict, float, Optional[np.ndarray]]:
        """
        Scan the image with overlapping patches at multiple scales to detect
        localized regions with inconsistent noise/sharpness statistics.

        AI inpainting typically modifies a localized region while leaving
        the rest of the image untouched. This creates a measurable
        discontinuity between the inpainted patch and its neighbors in:
        - Noise variance (median filter residual)
        - Laplacian sharpness energy
        - Local entropy

        Method:
            1. Extract overlapping patches across the image grid at multiple scales
            2. For each patch, compute noise_var and laplacian_var
            3. For each patch, compare against its spatial 3x3 neighbors
            4. Compute bidirectional disparity: max(patch/neighbor, neighbor/patch)
            5. Flag patches where disparity exceeds threshold
            6. Generate an inpainting anomaly heatmap overlay
        """
        h, w = gray.shape
        scales = (
            self.patch_sizes
            if hasattr(self, "patch_sizes") and self.patch_sizes
            else (self.patch_size,)
        )

        # Extract noise residual for entire image
        median_filtered = cv2.medianBlur(gray, 3)
        noise_residual = gray.astype(np.float64) - median_filtered.astype(np.float64)

        heatmap_accum = np.zeros((h, w), dtype=np.float64)
        counts = np.zeros((h, w), dtype=np.float64)

        total_patches = 0
        suspicious_patches = 0
        disparities = []
        suspicious_locations = []
        all_noise_vars = []
        all_lap_vars = []

        for ps in scales:
            if h < ps * 2 or w < ps * 2:
                continue
            stride = max(8, ps // 2)

            rows = list(range(0, h - ps + 1, stride))
            cols = list(range(0, w - ps + 1, stride))
            n_rows, n_cols = len(rows), len(cols)
            if n_rows < 3 or n_cols < 3:
                continue

            noise_grid = np.zeros((n_rows, n_cols))
            lap_grid = np.zeros((n_rows, n_cols))

            for ri, y in enumerate(rows):
                for ci, x in enumerate(cols):
                    patch_noise = noise_residual[y:y + ps, x:x + ps]
                    patch_gray = gray[y:y + ps, x:x + ps]
                    nv = float(np.var(patch_noise))
                    lv = float(np.var(cv2.Laplacian(patch_gray, cv2.CV_64F)))
                    noise_grid[ri, ci] = nv
                    lap_grid[ri, ci] = lv
                    all_noise_vars.append(nv)
                    all_lap_vars.append(lv)

            # Compare each patch against its 3x3 neighborhood
            for ri in range(n_rows):
                for ci in range(n_cols):
                    nbr_noise = []
                    nbr_lap = []

                    for dr in range(-1, 2):
                        for dc in range(-1, 2):
                            if dr == 0 and dc == 0:
                                continue
                            nr, nc = ri + dr, ci + dc
                            if 0 <= nr < n_rows and 0 <= nc < n_cols:
                                nbr_noise.append(noise_grid[nr, nc])
                                nbr_lap.append(lap_grid[nr, nc])

                    if not nbr_noise:
                        continue

                    med_n = float(np.median(nbr_noise))

                    # Compute regularized noise disparity using sensor noise floor baseline (eps_n = 4.0)
                    # This prevents division-by-zero explosions on smooth surfaces (e.g. flat car paint)
                    # while reliably capturing noise inconsistencies from neural inpainting
                    eps_n = 4.0
                    disp_n = (max(noise_grid[ri, ci], med_n) + eps_n) / (min(noise_grid[ri, ci], med_n) + eps_n)

                    patch_disp = float(disp_n)
                    disparities.append(patch_disp)
                    total_patches += 1

                    y_coord, x_coord = rows[ri], cols[ci]
                    # Accumulate into anomaly heatmap
                    heatmap_accum[y_coord:y_coord + ps, x_coord:x_coord + ps] += max(0.0, patch_disp - 1.0)
                    counts[y_coord:y_coord + ps, x_coord:x_coord + ps] += 1.0

                    if patch_disp > self.noise_disparity_threshold:
                        suspicious_patches += 1
                        suspicious_locations.append({
                            "scale": ps,
                            "row": ri,
                            "col": ci,
                            "y": y_coord,
                            "x": x_coord,
                            "noise_disparity": round(patch_disp, 2),
                            "max_disparity": round(patch_disp, 2),
                        })

        if total_patches == 0:
            return {
                "error": "Image too small for patch analysis",
                "image_size": (h, w),
            }, 75.0, None

        susp_ratio = suspicious_patches / total_patches
        max_disp = float(max(disparities)) if disparities else 1.0
        mean_disp = float(np.mean(disparities)) if disparities else 1.0

        noise_var_cv = float(
            np.std(all_noise_vars) / (np.mean(all_noise_vars) + 1e-8)
        ) if all_noise_vars else 0.0
        lap_var_cv = float(
            np.std(all_lap_vars) / (np.mean(all_lap_vars) + 1e-8)
        ) if all_lap_vars else 0.0

        metrics = {
            "total_patches": total_patches,
            "suspicious_patch_count": suspicious_patches,
            "suspicious_patch_ratio": round(susp_ratio, 4),
            "max_noise_disparity": round(max_disp, 2),
            "mean_noise_disparity": round(mean_disp, 2),
            "noise_variance_cv": round(noise_var_cv, 4),
            "laplacian_variance_cv": round(lap_var_cv, 4),
            "suspicious_locations_count": len(suspicious_locations),
        }

        score = self._score_patches(metrics)

        # Generate visual heatmap overlay
        overlay = None
        if orig_bgr is not None and np.any(counts > 0):
            valid = counts > 0
            norm_accum = np.zeros_like(heatmap_accum)
            norm_accum[valid] = heatmap_accum[valid] / counts[valid]
            p99 = np.percentile(norm_accum, 99) if np.max(norm_accum) > 0 else 1.0
            norm_map = np.clip(norm_accum / (p99 + 1e-6), 0.0, 1.0)
            colored = cv2.applyColorMap((norm_map * 255).astype(np.uint8), cv2.COLORMAP_JET)
            overlay = cv2.addWeighted(orig_bgr, 0.65, colored, 0.35, 0)

        return metrics, score, overlay

    def _score_patches(self, metrics: dict) -> float:
        """
        Score patch analysis metrics (0-100, higher = more natural/authentic).

        Key indicators of AI inpainting:
        - High suspicious patch ratio (many locally inconsistent regions)
        - High max noise disparity (extreme local discontinuity)
        - High CV of noise variance across patches (inconsistent noise field)
        """
        score = 100.0
        susp_ratio = metrics.get("suspicious_patch_ratio", 0.0)
        max_disp = metrics.get("max_noise_disparity", 1.0)
        noise_cv = metrics.get("noise_variance_cv", 0.0)

        # 1. Penalize high suspicious patch ratio (localized inpainting)
        if susp_ratio > 0.08:
            score -= 35.0
        elif susp_ratio > 0.03:
            score -= 20.0
        elif susp_ratio > 0.01:
            score -= 10.0

        # 2. Penalize extreme max disparity (sharp boundary discontinuity)
        if max_disp > 15.0:
            score -= 30.0
        elif max_disp > 10.0:
            score -= 20.0
        elif max_disp > 6.0:
            score -= 10.0

        # 3. Penalize high noise variance CV across image
        if noise_cv > 2.5:
            score -= 15.0
        elif noise_cv > 1.8:
            score -= 5.0

        return max(0.0, min(100.0, score))

    # ══════════════════════════════════════════════════════════════
    # UTILITY METHODS
    # ══════════════════════════════════════════════════════════════

    def _load_image(self, image_input) -> Optional[np.ndarray]:
        """Load image as BGR numpy array from various input types."""
        try:
            if isinstance(image_input, np.ndarray):
                if len(image_input.shape) == 2:
                    return cv2.cvtColor(image_input, cv2.COLOR_GRAY2BGR)
                return image_input

            if isinstance(image_input, (str, Path)):
                img = cv2.imread(str(image_input), cv2.IMREAD_COLOR)
                if img is None:
                    # Try unicode path fallback
                    raw = Path(image_input).read_bytes()
                    arr = np.frombuffer(raw, dtype=np.uint8)
                    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
                return img

            if isinstance(image_input, bytes):
                arr = np.frombuffer(image_input, dtype=np.uint8)
                return cv2.imdecode(arr, cv2.IMREAD_COLOR)

            if isinstance(image_input, io.BytesIO):
                arr = np.frombuffer(image_input.getvalue(), dtype=np.uint8)
                return cv2.imdecode(arr, cv2.IMREAD_COLOR)

            return None
        except Exception as e:
            logger.error("Failed to load image for AI detection: %s", e)
            return None
